DROP DATABASE IF EXISTS IPL_FANTASY_LEAGUE;
CREATE DATABASE IPL_FANTASY_LEAGUE;
USE IPL_FANTASY_LEAGUE;

CREATE TABLE PARTNER (
    CIN INT UNIQUE NOT NULL,
    Name VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT PARTNER_PK PRIMARY KEY(CIN)
);

CREATE TABLE PARTNER_TYPE (
    CIN INT UNIQUE NOT NULL,
    Type VARCHAR(40) NOT NULL,
    CONSTRAINT PARTNER_TYPE_PK PRIMARY KEY(CIN, Type),
    CONSTRAINT PARTNER_TYPE_FK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LEAGUE (
    Prize_Money INT NOT NULL DEFAULT 10000000,
    Runner_Up VARCHAR(20) NOT NULL,
    Winner VARCHAR(20) NOT NULL,
    Name VARCHAR(30) NOT NULL UNIQUE,
    Season_Number INT AUTO_INCREMENT UNIQUE NOT NULL,
    CONSTRAINT LEAGUE_PK PRIMARY KEY(Season_Number)
);

CREATE TABLE TEAM (
    Place VARCHAR(20) NOT NULL,
    RTM_Cards INT NOT NULL DEFAULT 0,
    Money_Left INT NOT NULL DEFAULT 0,
    Brand_Value INT NOT NULL DEFAULT 10000000,
    Fair_play_points DECIMAL(5, 2) NOT NULL DEFAULT 0,
    Total_points INT NOT NULL DEFAULT 0,
    Name VARCHAR(30) NOT NULL UNIQUE,
    Coach VARCHAR(20) NOT NULL UNIQUE,
    CONSTRAINT TEAM_PK PRIMARY KEY(Name)
);

CREATE TABLE TEAM_MANAGER (
    Manager_First_Name VARCHAR(20) NOT NULL,
    Manager_Last_Name VARCHAR(20) NOT NULL ,
    Name VARCHAR(30) NOT NULL,
    CONSTRAINT TEAM_MANAGER_PK PRIMARY KEY(Name),
    CONSTRAINT TEAM_MANAGER_UNIQUE UNIQUE(Manager_First_Name, Manager_Last_Name)
);

CREATE TABLE FIXTURE (
    Date_Time TIMESTAMP NOT NULL, 
    Venue VARCHAR(50) NOT NULL ,
    Result VARCHAR(30) NOT NULL,
    Match_No INT NOT NULL,
    CONSTRAINT FIXTURE_PK PRIMARY KEY(Date_Time, Venue)
);

CREATE TABLE UMPIRE (
    Date_Time TIMESTAMP NOT NULL, 
    Venue VARCHAR(50) NOT NULL ,
    Umpire_Name VARCHAR(20) NOT NULL UNIQUE,
    Umpire_Position INT NOT NULL,
    CONSTRAINT UMPIRE_PK PRIMARY KEY(Date_Time, Venue, Umpire_Name),
    CONSTRAINT UMPIRE_FK FOREIGN KEY (Date_Time, Venue) REFERENCES FIXTURE(Date_Time, Venue) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (Umpire_Position = 1 OR Umpire_Position = 2 OR Umpire_Position = 3)
);

CREATE TABLE FORM (
    Fantasy_points INT NOT NULL DEFAULT 0,
    Form DECIMAL(3, 1) NOT NULL DEFAULT 0,
    CONSTRAINT FORM_PK PRIMARY KEY(Fantasy_points)
);

CREATE TABLE PLAYER (
    Base_price INT NOT NULL,
    Auctioned_price INT NOT NULL DEFAULT 2000000,
    Name VARCHAR(40) NOT NULL UNIQUE,
    CName VARCHAR(40) NOT NULL,
    Fantasy_points INT NOT NULL DEFAULT 0,
    CONSTRAINT PLAYER_PK PRIMARY KEY(Name),
    CONSTRAINT PLAYER_Fantasy_points_FK
    FOREIGN KEY PLAYER(Fantasy_points) REFERENCES FORM(Fantasy_points),
    CONSTRAINT PLAYER_CName_FK
    FOREIGN KEY PLAYER(CName) REFERENCES PLAYER(Name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AWARDS (
    Prize_Money INT NOT NULL DEFAULT 100000,
    Name VARCHAR(20) NOT NULL,
    AWARDED_IN INT NOT NULL,
    AWARDED_TO VARCHAR(40) NOT NULL UNIQUE,
    CONSTRAINT AWARDS_PK PRIMARY KEY(Name, AWARDED_IN, AWARDED_TO),
    CONSTRAINT AWARDS_AWARDED_IN_FK
    FOREIGN KEY(AWARDED_IN) REFERENCES LEAGUE(Season_Number) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT AWARDS_AWARDED_TO_FK
    FOREIGN KEY(AWARDED_TO) REFERENCES PLAYER(Name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SPONSORS_PLAYER (
    Name VARCHAR(40) NOT NULL,
    CIN INT NOT NULL,
    CONSTRAINT SPONSORS_PLAYER_PK PRIMARY KEY(Name, CIN),
    CONSTRAINT SPONSORS_PLAYER_Name_FK 
    FOREIGN KEY(Name) REFERENCES PLAYER(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SPONSORS_PLAYER_CIN_FK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SPONSORS_LEAGUE (
    Number INT NOT NULL,
    CIN INT NOT NULL,
    CONSTRAINT SPONSORS_LEAGUE_PK PRIMARY KEY(Number, CIN),
    CONSTRAINT SPONSORS_LEAGUE_Number_FK 
    FOREIGN KEY(Number) REFERENCES LEAGUE(Season_Number) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SPONSORS_LEAGUE_CIN_FK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SPONSORS_TEAM (
    Name VARCHAR(30) NOT NULL,
    CIN INT NOT NULL,
    CONSTRAINT SPONSORS_TEAM_PK PRIMARY KEY(Name, CIN),
    CONSTRAINT SPONSORS_TEAM_Name_FK 
    FOREIGN KEY(Name) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SPONSORS_Team_CIN_FK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PLAYS_IN(
    Name VARCHAR(30) NOT NULL,
    Date_Time TIMESTAMP NOT NULL,
    Venue VARCHAR(50) NOT NULL,
    CONSTRAINT PLAYS_IN_PK PRIMARY KEY(Name, Date_Time, Venue),
    CONSTRAINT PLAYS_IN_Name_FK
    FOREIGN KEY(Name) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PLAYS_IN_Date_Time_Venue_FK
    FOREIGN KEY(Date_Time, Venue) REFERENCES FIXTURE(Date_Time, Venue) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PLAYS_FOR_IN_OF (
    PName VARCHAR(40) NOT NULL,
    TName VARCHAR(30) NOT NULL,
    Date_Time TIMESTAMP NOT NULL,
    Venue VARCHAR(50) NOT NULL,
    Season_Number INT NOT NULL,
    CONSTRAINT PLAYS_FOR_IN_OF_PK PRIMARY KEY(PName, TName, Date_Time, Venue, Season_Number),
    CONSTRAINT PLAYS_FOR_IN_OF_PName_FK
    FOREIGN KEY(PName) REFERENCES PLAYER(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PLAYS_FOR_IN_OF_TName_FK
    FOREIGN KEY(TName) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PLAYS_FOR_IN_OF_Date_Time_Venue_FK
    FOREIGN KEY(Date_Time, Venue) REFERENCES FIXTURE(Date_Time, Venue) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PLAYS_FOR_IN_OF_Season_Number_FK
    FOREIGN KEY(Season_Number) REFERENCES LEAGUE(Season_Number) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMMENTATORS(
    Date_Time TIMESTAMP NOT NULL,
    Venue VARCHAR(50) NOT NULL,
    Commentators VARCHAR(30) NOT NULL,
    CONSTRAINT COMMENTATORS_PK PRIMARY KEY(Date_Time, Venue, Commentators),
    CONSTRAINT COMMENTATORS_Date_Time_Venue_FK
    FOREIGN KEY(Date_Time, Venue) REFERENCES FIXTURE(Date_Time, Venue) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE JERSEY(
    Jersey_Number INT NOT NULL,
    BELONGS_TO VARCHAR(30) NOT NULL,
    CONSTRAINT JERSEY_PK PRIMARY KEY(Jersey_Number, BELONGS_TO),
    CONSTRAINT JERSEY_BELONGS_TO_FK
    FOREIGN KEY(BELONGS_TO) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE
);