CREATE TABLE PARTNER (
    CIN INT UNIQUE NOT NULL,
    Name VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT PARTPK PRIMARY KEY(CIN)
);

CREATE TABLE PARTNER_TYPE(
    CIN INT UNIQUE NOT NULL,
    Type VARCHAR(40) NOT NULL,
    CONSTRAINT PART_TYPEPK PRIMARY KEY(CIN,Type),
    CONSTRAINT PART_TYPEFK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LEAGUE (
    Prize_Money INT NOT NULL DEFAULT 10000000,
    Runner_Up VARCHAR(20) NOT NULL,
    Winner VARCHAR(20) NOT NULL,
    Name VARCHAR(30) NOT NULL UNIQUE,
    Season_Number INT AUTO_INCREMENT UNIQUE NOT NULL,
--    constraints
    CONSTRAINT LEAGUEPK PRIMARY KEY(Season_Number)
);

DROP TABLE TEAM;
CREATE TABLE TEAM (
    Place VARCHAR(20) NOT NULL,
    RTM_Cards INT NOT NULL DEFAULT 0,
    Money_Left INT NOT NULL DEFAULT 0,
    Brand_Value INT NOT NULL,
    Fair_play_points DECIMAL(5,2) NOT NULL DEFAULT 0,
    Total_points INT NOT NULL DEFAULT 0,
    Name VARCHAR (30) NOT NULL UNIQUE,
    Coach VARCHAR(20) NOT NULL UNIQUE,
    -- constraints
    CONSTRAINT TPK PRIMARY KEY(Name)
);

CREATE TABLE TEAM_MANAGER(
    Manager_First_Name VARCHAR(20) NOT NULL,
    Manager_Last_Name VARCHAR(20) ,
    Name VARCHAR (30),
    -- constraints 
    CONSTRAINT TManPK PRIMARY KEY(Name),
    CONSTRAINT ManKey UNIQUE(Manager_First_Name,Manager_Last_Name)
);

CREATE TABLE FIXTURE(
    Date_Time TIMESTAMP NOT NULL, 
    Venue VARCHAR(50) NOT NULL ,
    Result VARCHAR(30) NOT NULL,
    Match_No INT NOT NULL,
    CONSTRAINT Date_Time_VenuePK PRIMARY KEY(Date_Time,Venue)
);

CREATE TABLE UMPIRE(
    Date_Time TIMESTAMP NOT NULL, 
    Venue VARCHAR(50) NOT NULL ,
    Umpire_Name VARCHAR(20) NOT NULL UNIQUE,
    Umpire_Position INT NOT NULL,
    CONSTRAINT UmpirePK PRIMARY KEY(Date_Time, Venue, Umpire_Name),
    -- CONSTRAINT Umpire_Date_TimeFK 
    -- FOREIGN KEY(Date_Time) REFERENCES FIXTURE(Date_Time) ON DELETE CASCADE ON UPDATE CASCADE,
    -- CONSTRAINT Umpire_VenueFK
    -- FOREIGN KEY(Venue) REFERENCES FIXTURE(Venue) ON DELETE CASCADE ON UPDATE CASCADE
    CONSTRAINT FK FOREIGN KEY (Date_Time,Venue) REFERENCES FIXTURE(Date_Time,Venue)
);


CREATE TABLE AWARDS(
    Prize_Money INT NOT NULL DEFAULT 100000,
    Name VARCHAR(40) NOT NULL,
    AWARDED_IN INT NOT NULL,
    AWARDED_TO VARCHAR(40) NOT NULL UNIQUE,
    CONSTRAINT AwardPK PRIMARY KEY(Name, AWARDED_IN, AWARDED_TO),
    CONSTRAINT Awarded_In_LeagueFK
    FOREIGN KEY(AWARDED_IN) REFERENCES LEAGUE(Season_Number) ON DELETE CASCADE,
    CONSTRAINT Awarded_To_PlayerFK
    FOREIGN KEY(AWARDED_TO) REFERENCES PLAYER(Name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SPONSORS_PLAYER(
    Name VARCHAR(40) NOT NULL,
    CIN INT NOT NULL,
    CONSTRAINT SPONSORS_PLAYERPK PRIMARY KEY(Name,CIN),
    CONSTRAINT SPONSORS_PLAYER_NameFK 
    FOREIGN KEY(Name) REFERENCES PLAYER(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SPONSORS_PLAYER_CINFK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SPONSORS_LEAGUE(
    Number INT NOT NULL,
    CIN INT NOT NULL,
    CONSTRAINT SPONSORS_LEAGUEPK PRIMARY KEY(Number,CIN),
    CONSTRAINT SPONSORS_LEAGUE_NumberFK 
    FOREIGN KEY(Number) REFERENCES LEAGUE(Season_Number) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SPONSORS_LEAGUE_CINFK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SPONSORS_TEAM(
    Name VARCHAR(30)  NOT NULL,
    CIN INT NOT NULL,
    CONSTRAINT SPONSORS_TEAMPK PRIMARY KEY(Name,CIN),
    CONSTRAINT SPONSORS_TEAM_NameFK 
    FOREIGN KEY(Name) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SPONSORS_Team_CINFK
    FOREIGN KEY(CIN) REFERENCES PARTNER(CIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PLAYER (
    Base_price INT NOT NULL,
    Auctioned_price INT NOT NULL DEFAULT 2000000,
    Name VARCHAR(40) NOT NULL UNIQUE,
    CName VARCHAR(40) NOT NULL,
    Fantasy_points INT NOT NULL DEFAULT 0,
    -- constraints
    CONSTRAINT PPK PRIMARY KEY (Name),
    CONSTRAINT FORMFK FOREIGN KEY PLAYER(Fantasy_points) REFERENCES FORM(Fantasy_points)
);

CREATE TABLE FORM (
    Fantasy_points INT NOT NULL DEFAULT 0,
    Form DECIMAL(3, 1) NOT NULL UNIQUE,
    -- constraints
    CONSTRAINT FANTPK PRIMARY KEY ( Fantasy_points)
);

CREATE TABLE PLAYS_IN(
    Name VARCHAR(30) NOT NULL,
    Date_Time TIMESTAMP NOT NULL,
    Venue VARCHAR(50) NOT NULL,
    CONSTRAINT PLAYS_INPK PRIMARY KEY(Name,Date_Time,Venue),
    CONSTRAINT PLAYS_IN_NameFK
    FOREIGN KEY(Name) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PLAYS_INDate_Time_VenueFK
    FOREIGN KEY(Date_Time,Venue) REFERENCES FIXTURE(Date_Time,Venue) ON DELETE CASCADE ON UPDATE CASCADE
    -- CONSTRAINT PLAYS_INVenueFK
    -- FOREIGN KEY(Venue) REFERENCES FIXTURE(Venue) ON DELETE CASCADE ON UPDATE CASCADE
);
-- Umpire , commentators must be modified

CREATE TABLE PLAYS_FOR_IN_OF (
    PName VARCHAR(40) NOT NULL,
    TName VARCHAR(30) NOT NULL,
    Date_Time TIMESTAMP NOT NULL,
    Venue VARCHAR(50) NOT NULL,
    Season_Number INT NOT NULL,
    CONSTRAINT PLAYS_FOR_IN_OF_PK PRIMARY KEY(PName, TName, Date_Time, Venue, Season_Number),
    CONSTRAINT PName_FK
    FOREIGN KEY(PName) REFERENCES PLAYER(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT TName_FK
    FOREIGN KEY(TName) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT Date_Time_Venue_FK
    FOREIGN KEY(Date_Time, Venue) REFERENCES FIXTURE(Date_Time, Venue) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT Season_Number_FK
    FOREIGN KEY(Season_Number) REFERENCES LEAGUE(Season_Number) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMMENTATORS(
    Date_Time TIMESTAMP NOT NULL,
    Venue VARCHAR(30) NOT NULL,
    Commentators VARCHAR(30) NOT NULL,
    CONSTRAINT COMMENTATORSPK PRIMARY KEY(Date_Time,Venue,Commentators),
    CONSTRAINT COMMENTATORS_Date_Time_VenueFK
    FOREIGN KEY(Date_Time,Venue) REFERENCES FIXTURE(Date_Time,Venue) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE JERSEY(
    Jersey_Number INT NOT NULL,
    BELONGS_TO VARCHAR(30) NOT NULL,
    CONSTRAINT JERSEY_PK PRIMARY KEY(Jersey_Number, BELONGS_TO),
    CONSTRAINT BELONGS_TO_FK
    FOREIGN KEY (BELONGS_TO) REFERENCES TEAM(Name) ON DELETE CASCADE ON UPDATE CASCADE
);